{% set name = "jupyterlab-autosave-on-focus-change" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_autosave_on_focus_change-{{ version }}.tar.gz
  sha256: 54bbec282cfe56f50566e7ed7caf51c98db7280695da97efc089b981622964c9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab >=4.0.0,<5
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab_autosave_on_focus_change.*OK"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  summary: Jupyterlab extension to autosave files on focus change
  dev_url: https://github.com/s-weigand/jupyterlab_autosave_on_focus_change
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
